name: renovate

on:
  schedule:
    - cron: "0 10 * * 5" # JST 19:00 (Fri)
  workflow_dispatch:

jobs:
  renovate:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: ".github/renovate.json"
