name: test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: "0 10 * * 5" # JST 19:00 (Fri)
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.3"
          - "3.4"
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs $(nproc) --retry 3
      - name: test
        run: |
          bundle exec rake

